- r: 0.288
  g: 0.240
  b: 0.192
  size: 0.413
  label: wall
- r: 0.154
  g: 0.153
  b: 0.192
  size: 0.286
  label: asus-box
- r: 0.110
  g: 0.108
  b: 0.143
  size: 0.087
  label: asus-box
- r: 0.189
  g: 0.317
  b: 0.050
  size: 0.236
  label: kinect-box
- r: 0.629
  g: 0.566
  b: 0.478
  size: 0.121
  label: kinect-label
- r: 0.529
  g: 0.521
  b: 0.434
  size: 0.106
  label: kinect-label
- r: 0.204
  g: 0.102
  b: 0.093
  size: 0.100
  label: ice-cream
- r: 0.618
  g: 0.534
  b: 0.274
  size: 0.096
  label: kinect-label
- r: 0.139
  g: 0.034
  b: 0.149
  size: 0.163
  label: kinect-adapter-box
- r: 0.133
  g: 0.036
  b: 0.156
  size: 0.131
  label: kinect-adapter-box
- r: 0.652
  g: 0.429
  b: 0.109
  size: 0.086
  label: lemon
- r: 0.590
  g: 0.393
  b: 0.180
  size: 0.092
  label: ice-cream-cone
- r: 0.628
  g: 0.524
  b: 0.403
  size: 0.124
  label: tape
- r: 0.682
  g: 0.591
  b: 0.549
  size: 0.114
  label: table
- r: 0.633
  g: 0.556
  b: 0.512
  size: 0.110
  label: table
- r: 0.748
  g: 0.665
  b: 0.609
  size: 0.104
  label: table
